"""crea tablas orders y order_items, agrega order_id a purchases

Revision ID: f0180ac18a07
Revises: c8ee0f8a840e
Create Date: 2026-07-29 17:40:10.034304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0180ac18a07'
down_revision: Union[str, Sequence[str], None] = 'c8ee0f8a840e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='ARS', nullable=False),
    sa.Column('cancellation_code', sa.String(length=64), nullable=False),
    sa.Column('provider_preference_id', sa.String(length=64), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency IN ('ARS')", name='ck_orders_currency'),
    sa.CheckConstraint("status IN ('pending', 'paid', 'failed', 'refunded', 'expired', 'partially_refunded')", name='ck_orders_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cancellation_code'),
    sa.UniqueConstraint('provider_payment_id'),
    sa.UniqueConstraint('provider_preference_id')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index('uq_orders_una_pending_por_usuario', 'orders', ['user_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('order_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'course_id', name='uq_order_items_order_course')
    )
    op.create_index(op.f('ix_order_items_course_id'), 'order_items', ['course_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.add_column('purchases', sa.Column('order_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_purchases_order_id'), 'purchases', ['order_id'], unique=False)
    op.create_foreign_key(None, 'purchases', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('purchases_order_id_fkey', 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_order_id'), table_name='purchases')
    op.drop_column('purchases', 'order_id')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_course_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('uq_orders_una_pending_por_usuario', table_name='orders', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
